# Generated by Django 4.2.16 on 2024-09-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
