# Generated by Django 4.2.16 on 2024-09-20 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
